Maintestbutton
SeregaLucky/project_pro_test_frontend pull request #10
Opened 2020-01-21 10:30 UTC by allacleo

2020-01-21 19:05 UTC, allacleo commented
All neccessary ammendment have been done so far

2020-01-21 21:38 UTC, SeregaLucky commented on src/components/MainTestButton/MainTestButton.js
> +      <ul>
Удали <ul>. Оставь <li> и то что в нем

2020-01-21 21:39 UTC, SeregaLucky commented on src/components/MainTestButton/MainTestButton.js
> +      <ul>
Удали ul. Оставь li и то что в нем

2020-01-21 21:41 UTC, SeregaLucky requested changes
Удали только ul. И оставь ди и то что в нем. И удали div которые их обворачивает

2020-01-22 08:23 UTC, allacleo commented on src/components/MainTestButton/MainTestButton.js
> +      <ul>
done

2020-01-22 08:59 UTC, merged