dashboardpage
SeregaLucky/project_pro_test_frontend pull request #15
Opened 2020-01-21 17:29 UTC by sergeypoddubnii

2020-01-21 21:44 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.js
> +    <div className={styles.dashboardPageContainer}>
Тут сделай не <div> а тегом <section>

2020-01-21 21:46 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.module.css
> +}
Удалить. Так нельзя написав так ты сделаешь что у всего проекта будет такой цвет бекгрунда. Так что удаляй не думая

2020-01-21 21:46 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.module.css
> +}
Тоже самое ты так прописав что у всех кнопок на проекте будет эти свойства. Так не правильно. Удаляй.

2020-01-21 21:47 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.module.css
> +}
Поправь ширину и добавь паддинг
width: 320px;
padding: 0 20px;

2020-01-21 21:49 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.module.css
> +@media screen and (min-width: 992px) {
Медиа не правильное. @media screen and (min-width: 1280px)

2020-01-21 21:51 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.js
> +        </h1>
не h1 а h2.

2020-01-21 22:01 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.module.css
> +  height: 100px;
margin: указать только в них маржин
height: 100px; - убрать

2020-01-21 22:02 UTC, SeregaLucky requested changes
Пока что сделай те поправки которые я написал. Постарайся завтра что бы уже было исправлено. что бы завтра или после завтра мог уже принять=)

2020-01-22 11:37 UTC, SeregaLucky requested changes
Поправь)

2020-01-22 21:49 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.js
> +    <div className={styles.dashboardPage}>
Вместо тега div нужен тег section

2020-01-22 21:50 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.module.css
> +  background-color: #f4f6fb;
Добавь padding для вверха и для низа

2020-01-22 21:51 UTC, SeregaLucky commented on src/pages/DashboardPage/DashboardPage.module.css
> +  padding-bottom: 20px;
а тут как раз убрать padding

2020-01-22 21:52 UTC, SeregaLucky requested changes
Пару правок сделай которые в коде написал

2020-01-23 06:15 UTC, sergeypoddubnii commented
пофиксил

2020-02-04 20:23 UTC, closed without merging